### PR TITLE
Added space travel suggestion.

### PR DESCRIPTION
**Pull request by acolangelo**
An extremely large majority of space launches include enormous vehicles being discarded into oceans or deserts. They’re used once, and then thrown away destructively. The only way to improve this is to land said vehicles and reuse them multiple times.

### CODE REVIEW

**Comment by pmarsceill** [comment]
Please provided a meaningful description for this pull request.

**Comment by acolangelo** [comment]
@pmarsceill thanks, edited.

**Comment by olivierlacan** [comment]
> Please provided a meaningful description for this pull request.

Please fix typo in Issue comment. :trollface:

**Comment by olivierlacan** [comment]
🚀 👩‍🚀 🌍 🛰

**Pull request merged**
